# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186a13b8866ac089efd54436c8b6ae4d67a70299ed0c2119958eccca151abcbc22ae1aad70850d977aecd9f2b4975216992b0e52a9e7a8b26f067c416b96502c

test:
  secret_key_base: 1bdc01862f7378a14fc20455845c12a87adf7410884c0caa753ed0a96d348a143db3aace0f76f0f7478a7ed446031531f1780638815c6b00a8bdc80144cabc11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
